spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://chamod-user:-_PXrMRQCFwtJH_6VrBPHPVi6PL_DyUaqA3TZIo-x99Q-w1R@c77abc48-d1f0-4ffa-8306-069458c638bf.asia-southeast1.firestore.goog:443/database-1?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}